
AWSTemplateFormatVersion: 2010-09-09
Description: Test cloudformation template
Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole

  Client:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: test.overattribution.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-api

  UserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref API
      ParentId:
        !GetAtt
          - API
          - RootResourceId
      PathPart: users

  UserFunction:
    DependsOn: LambdaExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UserFunction
      Description: UserFunction
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
            callback(null, {
              statusCode: 200,
              body: JSON.stringify({
                username: 'corey'
              })
            });
          };
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs6.10
      Timeout: 3

  UserFunctionPermission:
    DependsOn: UserFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: UserFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: API
          - "/*/GET/*"

  UserResourceAny:
    DependsOn: UserFunction
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref UserResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
          - Arn:
              Fn::GetAtt:
              - UserFunction
              - Arn
